######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 11 11:58:19 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += ../../lib/bin ../../lib/inc
LIBS += -L../../lib/bin/ -ltimelab -lportaudio -ldl

# Input
HEADERS += globals.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp setup.c
