######################################################################
# Automatically generated by qmake (2.01a) Fri Nov 7 12:47:38 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += ../../lib/bin ../../lib/inc
LIBS += -L../../lib/bin/ -ltimelab

# Input
HEADERS += mainwindow.h ui.h
FORMS += mainwindow.ui test_ctl.ui
SOURCES += main.cpp mainwindow.cpp setup.c

